In [52]:
import torch
from torch.nn.parameter import Parameter
import numpy as np

In [53]:
torch.manual_seed(0)
num_v = 10 # totally num of vacabuliries of whole bag, so idx [0,V)
# x: (N, T) gives index of whole bag voc, gives one idx.
x = torch.randint(num_v, (2,3))
# out: (N, T, D),
vacab_size = num_v
out = Parameter(torch.randn(vacab_size, 5))
print(x)
out[x], out[x, 1]

tensor([[4, 9, 3],
        [0, 3, 9]])


(tensor([[[ 1.4437,  0.2660,  0.1665,  0.8744,  0.9463],
          [-0.4949, -1.4959, -0.1938,  0.4455,  1.3253],
          [-0.3090, -0.3414,  1.8530,  0.4681, -0.1577]],
 
         [[-0.3160, -2.1152, -0.3561,  0.4372,  0.4913],
          [-0.3090, -0.3414,  1.8530,  0.4681, -0.1577],
          [-0.4949, -1.4959, -0.1938,  0.4455,  1.3253]]],
        grad_fn=<IndexBackward>),
 tensor([[ 0.2660, -1.4959, -0.3414],
         [-2.1152, -0.3414, -1.4959]], grad_fn=<IndexBackward>))

In [65]:
test_a = np.random.randn(3, 1)
test_b = np.random.randn(3, 1)
print(test_a.dot(test_b.T))
np.dot(test_a, test_b.T)
test_a[1][3,0]

[[-0.19186327 -0.38144495  0.89455107]
 [-0.23598714 -0.46916798  1.10027599]
 [-0.11443502 -0.22750921  0.53354648]]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed